import numpy as np
import h5py

def load_image(path, frame_idxs, subpixels):
    # Parse the suboffset.
    # TODO: Make it default to whole image.
    suboffset = [int(x) for x in subpixels.split('x')]
    assert len(suboffset) == 4
    subpixels = (suboffset[2], suboffset[3])
    suboffset = (suboffset[0], suboffset[1])

    # Read frames.
    # These must be generated by clean_image.py.
    with h5py.File(path, 'r') as vf:
        frames = vf['frames'][:]
        times = vf['times'][:]
        tfilter = vf['tfilter'][:]
        filter_dark = vf['filter_dark'][:]

        images = [frames[idx]
                  [suboffset[0]:suboffset[0] + subpixels[0],
                   suboffset[1]:suboffset[1] + subpixels[1]]
                  for idx in frame_idxs]

    return frames, times, tfilter, filter_dark, images
